// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcgsohkbhnjhnfdmjokq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjZ3NvaGtiaG5qaG5mZG1qb2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjM5MjksImV4cCI6MjA2NDg5OTkyOX0.qGcCS6cbNlKzzbGfle4u7TYguLVNKIEMMMK2yi8f8sY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);